name: ci-nodejs-workflow

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - uses: actions/setup-node@v4
      - name: Setup Node.js 18
        with:
          node-version: 18

      - run: npm test
      - run: npm start